image: node:18

pages:
  script:
    - cd docs
    - npm install
    - npx vitepress build
    - mkdir -p public
    - cp -r .vitepress/dist/* public/
  artifacts:
    paths:
      - public
  only:
    - docs
