on:
  push:
    branches:
      - docs

name: master

jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: cd docs && npm install --force

      - name: Build website
        run: cd docs && npm run docs:build

      - name: Deploy
        run: cd docs && npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
